---
- name: "Playbook to Add Key to EC2 Instances"
  hosts: tomcat_server
  vars:
    - status : "present"
    - key : "~/.ssh/id_rsa.pub"

  tasks:

  - name: "Copy the authorized key file from"
    authorized_key:
      user: ubuntu
      state: present
      key: "{{ lookup('file', '{{ key }}')}}"
